### ISSUE TITLE
Foot and Mouth Study

### ISSUE THREAD

**Issue by cviddy17** [trevwj/intro-data-capstone-biodiversity#4]
The study was presented well, but the numbers were a little lacking for the overall presentation slide. The 33.3 % was overall ignored in the findings, but the two week recommendation was correct.

**Comment by trevwj** [comment]
I forgot to add the 33.3%. Thank you for pointing it out.

**Comment by trevwj** [comment]
Do I need to go back and reset this with the numbers?
